# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1paWueh6Uyx1K59LZY_qboLc4Y50pPLpy
"""

import pandas as pd
from matplotlib import pyplot as plt
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, RepeatVector, TimeDistributed, Dense
import random
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import (
    Input,
    LSTM,
    RepeatVector,
    TimeDistributed,
    Dense,
    Dropout
)
from tensorflow.keras.optimizers import Adam

SEED = 42

random.seed(SEED)
np.random.seed(SEED)
tf.random.set_seed(SEED)

df = pd.read_csv(r"C:\Users\alex_\Desktop\Fraud Detection Dataset.csv")

df.shape

df.columns

tx_per_account = (
    df.groupby("customer_id")
      .size()
)

print(
    tx_per_account.describe(
        percentiles=[0.25, 0.50, 0.75, 0.90, 0.95, 0.99]
    )
)

plt.figure(figsize=(10, 5))

plt.hist(
    tx_per_account,
    bins=25
)

plt.xlabel("Número de transacciones por cuenta")
plt.ylabel("Número de cuentas")
plt.title("Distribución de transacciones por cuenta")

plt.show()

for n in [1, 2, 5, 10, 15, 20, 30, 50, 100]:
    count = (tx_per_account >= n).sum()
    pct = count / len(tx_per_account) * 100

    print(
        f">= {n:3} transacciones: "
        f"{count:,} cuentas ({pct:.2f}%)"
    )

p99 = tx_per_account.quantile(0.99)

plt.figure(figsize=(10, 5))

plt.hist(
    tx_per_account[tx_per_account <= p99],
    bins=50
)

plt.xlabel("Número de transacciones por cuenta")
plt.ylabel("Número de cuentas")
plt.title("Distribución de transacciones por cuenta hasta P99")

plt.show()

df_original = df.copy()

df_original

df["timestamp"] = pd.to_datetime(
    df["timestamp"],
    utc=True,
    errors="coerce"
)

df = (
    df.sort_values(["customer_id", "timestamp"])
      .reset_index(drop=True)
)

delta_seconds = (
    df.groupby("customer_id")["timestamp"]
      .diff()
      .dt.total_seconds()
)

df["has_previous_tx"] = (
    delta_seconds.notna()
).astype("int8")

delta_hours = (
    delta_seconds / 3600
)

df["log_delta_hours"] = np.log1p(
    delta_hours
      .fillna(0)
      .clip(lower=0)
)

hour = (
    df["timestamp"].dt.hour
    + df["timestamp"].dt.minute / 60
    + df["timestamp"].dt.second / 3600
)

df["hour_sin"] = np.sin(
    2 * np.pi * hour / 24
)

df["hour_cos"] = np.cos(
    2 * np.pi * hour / 24
)

day_of_week = (
    df["timestamp"].dt.dayofweek
)

df["dow_sin"] = np.sin(
    2 * np.pi * day_of_week / 7
)

df["dow_cos"] = np.cos(
    2 * np.pi * day_of_week / 7
)

df.drop(columns='timestamp')

df['currency'].value_counts()

previous_device = (
    df.groupby("customer_id")["device_id"]
      .shift(1)
)

df["device_changed"] = (
    previous_device.notna()
    & (df["device_id"] != previous_device)
).astype("int8")

df["device_seen_before"] = (
    df.groupby(["customer_id", "device_id"])
      .cumcount()
)

df["is_new_device"] = (
    df["device_seen_before"] == 0
).astype("int8")

df

previous_ip = (
    df.groupby("customer_id")["ip_address"]
      .shift(1)
)

df["ip_changed"] = (
    previous_ip.notna()
    & (df["ip_address"] != previous_ip)
).astype("int8")

df["ip_seen_before"] = (
    df.groupby(["customer_id", "ip_address"])
      .cumcount()
)

df["is_new_ip"] = (
    df["ip_seen_before"] == 0
).astype("int8")

df.shape

previous_card = (
    df.groupby("customer_id")["card_id"]
      .shift(1)
)

df["card_changed"] = (
    previous_card.notna()
    & (df["card_id"] != previous_card)
).astype("int8")

df["card_seen_before"] = (
    df.groupby(["customer_id", "card_id"])
      .cumcount()
)

df["is_new_card"] = (
    df["card_seen_before"] == 0
).astype("int8")

previous_merchant = (
    df.groupby("customer_id")["merchant_id"]
      .shift(1)
)

df["merchant_changed"] = (
    previous_merchant.notna()
    & (df["merchant_id"] != previous_merchant)
).astype("int8")

df["merchant_seen_before"] = (
    df.groupby(["customer_id", "merchant_id"])
      .cumcount()
)

df["is_new_merchant"] = (
    df["merchant_seen_before"] == 0
).astype("int8")

df.columns

categorical_features = [
    "transaction_type",
    "merchant_category",
    "merchant_country",
]

df = pd.get_dummies(
    df,
    columns=categorical_features,
    prefix=categorical_features,
    dtype="int8"
)

df.shape

df.columns

df["log_amount"] = np.log1p(
    df["amount"].clip(lower=0)
)

df.shape

numeric_df = df.select_dtypes(include=["number", "bool"]).copy()

# No incluir target en el mapa de redundancia entre features
numeric_df = numeric_df.drop(
    columns=["is_fraud"],
    errors="ignore"
)

corr_matrix = numeric_df.corr()

print(corr_matrix.shape)

plt.figure(figsize=(22, 18))

plt.imshow(
    corr_matrix,
    aspect="auto",
    interpolation="nearest"
)

plt.colorbar(label="Correlación")

plt.xticks(
    range(len(corr_matrix.columns)),
    corr_matrix.columns,
    rotation=90,
    fontsize=8
)

plt.yticks(
    range(len(corr_matrix.columns)),
    corr_matrix.columns,
    fontsize=8
)

plt.title("Matriz de correlación entre features")
plt.tight_layout()
plt.show()

cols_to_drop = [
    "device_changed",
    "device_seen_before",
    "ip_changed",
    "ip_seen_before",
    "card_changed",
    "card_seen_before",
    "merchant_changed",
    "merchant_seen_before",
    "transaction_type_purchase",
    "merchant_latitude",
    "merchant_longitude",
    "amount"
]

df_correlation = df.drop(
    columns=cols_to_drop,
    errors="ignore"
)

df_correlation.columns

model_features = [
    "has_previous_tx",
    "log_delta_hours",
    "hour_sin",
    "hour_cos",
    "dow_sin",
    "dow_cos",

    "is_new_device",
    "is_new_ip",
    "is_new_card",
    "is_new_merchant",

    "transaction_type_transfer",
    "log_amount",
]

model_features += [
    col for col in df.columns
    if col.startswith("merchant_category_")
    or col.startswith("merchant_country_")
]

x = df[model_features].copy()
y = df["is_fraud"].copy()

x

train_split = int(len(x) * 0.70)
val_split = int(len(x) * 0.15)

x_train = x.iloc[:train_split].copy()
y_train = y.iloc[:train_split].copy()

x_val = x.iloc[
    train_split:train_split + val_split
].copy()

y_val = y.iloc[
    train_split:train_split + val_split
].copy()

x_test = x.iloc[
    train_split + val_split:
].copy()

y_test = y.iloc[
    train_split + val_split:
].copy()

normal_mask = y_train == 0

x_train = x_train[normal_mask]
y_train = y_train[normal_mask]

def create_sequences(x, customer_ids, timesteps=10):
    sequences = []

    temp = x.copy()
    temp["customer_id"] = customer_ids

    for customer_id, group in temp.groupby("customer_id"):
        features = group.drop(columns="customer_id").values

        if len(features) < timesteps:
            continue

        for i in range(len(features) - timesteps + 1):
            sequence = features[i:i + timesteps]
            sequences.append(sequence)

    return np.array(sequences)

x_train_seq = create_sequences(
    x_train,
    df.loc[x_train.index, "customer_id"],
    timesteps=10
)

x_val_seq = create_sequences(
    x_val,
    df.loc[x_val.index, "customer_id"],
    timesteps=10
)

x_test_seq = create_sequences(
    x_test,
    df.loc[x_test.index, "customer_id"],
    timesteps=10
)

len(x)


timesteps = x_train_seq.shape[1]
n_features = x_train_seq.shape[2]

model = Sequential([

    Input(shape=(timesteps, n_features)),

    # Encoder
    LSTM(
        128,
        activation="tanh",
        return_sequences=True
    ),

    Dropout(0.3),

    LSTM(
        64,
        activation="tanh",
        return_sequences=False
    ),

    # Latent -> secuencia
    RepeatVector(timesteps),

    # Decoder
    LSTM(
        64,
        activation="tanh",
        return_sequences=True
    ),

    Dropout(0.3),

    LSTM(
        128,
        activation="tanh",
        return_sequences=True
    ),

    # Reconstrucción
    TimeDistributed(
        Dense(n_features)
    )
])

model.compile(
    optimizer='adam',
    loss='mse',
    metrics=['accuracy']
)

model.summary()

history = model.fit(
    x_train_seq,
    x_train_seq,
    validation_data=(
        x_val_seq,
        x_val_seq
    ),
    epochs=20,
    batch_size=128,
    shuffle=False,
)

plt.figure(figsize=(10, 6))

plt.plot(
    history.history["loss"],
    label="Train Loss"
)

plt.plot(
    history.history["val_loss"],
    label="Validation Loss"
)

plt.xlabel("Época")
plt.ylabel("MSE Loss")
plt.title("Train vs Validation Loss")
plt.legend()
plt.grid(alpha=0.3)

plt.show()

def create_sequences_with_labels(x, y, customer_ids, timesteps=10):
    sequences = []
    labels = []

    temp = x.copy()
    temp["customer_id"] = customer_ids
    temp["target"] = y

    for customer_id, group in temp.groupby("customer_id"):
        features = group.drop(
            columns=["customer_id", "target"]
        ).values

        targets = group["target"].values

        if len(features) < timesteps:
            continue

        for i in range(len(features) - timesteps + 1):
            sequences.append(
                features[i:i + timesteps]
            )

            labels.append(
                targets[i + timesteps - 1]
            )

    return np.array(sequences), np.array(labels)

x_val_seq, y_val_seq = create_sequences_with_labels(
    x_val,
    y_val,
    df.loc[x_val.index, "customer_id"],
    timesteps=10
)

x_val_pred = model.predict(
    x_val_seq,
    verbose=0
)

val_error = np.mean(
    np.square(
        x_val_seq - x_val_pred
    ),
    axis=(1, 2)
)

normal_errors = val_error[
    y_val_seq == 0
]

fraud_errors = val_error[
    y_val_seq == 1
]

print("Normal:")
print("Mean:", normal_errors.mean())
print("Median:", np.median(normal_errors))

print("\nFraud:")
print("Mean:", fraud_errors.mean())
print("Median:", np.median(fraud_errors))

"""#Reconstruccion del riesgo"""

x_val_reconstructed = model.predict(
    x_val_seq,
    verbose=0
)

print(x_val_seq.shape)
print(x_val_reconstructed.shape)

reconstruction_error_val = np.mean(
    np.square(
        x_val_seq - x_val_reconstructed
    ),
    axis=(1, 2)
)

print(
    reconstruction_error_val[:10]
)

print(
    "Mean:",
    reconstruction_error_val.mean()
)

print(
    "Median:",
    np.median(reconstruction_error_val)
)

print(
    "Min:",
    reconstruction_error_val.min()
)

print(
    "Max:",
    reconstruction_error_val.max()
)

# reconstruction_error_val ya lo calculaste antes

normal_reference_errors = reconstruction_error_val[
    y_val_seq == 0
]

normal_reference_errors = np.sort(
    normal_reference_errors
)

print(normal_reference_errors.shape)

def reconstruction_to_risk(
    reconstruction_errors,
    reference_errors
):
    reconstruction_errors = np.asarray(
        reconstruction_errors
    )

    reference_errors = np.asarray(
        reference_errors
    )

    risk_scores = np.searchsorted(
        reference_errors,
        reconstruction_errors,
        side="right"
    ) / len(reference_errors)

    return risk_scores

val_risk_score = reconstruction_to_risk(
    reconstruction_error_val,
    normal_reference_errors
)

print(val_risk_score[:10])

print("Min:", val_risk_score.min())
print("Max:", val_risk_score.max())
print("Mean:", val_risk_score.mean())

import joblib

artifacts = {
    "reference_errors": normal_reference_errors,
    "features": model_features,
    "timesteps": timesteps,
}

joblib.dump(
    artifacts,
    r"C:\Users\alex_\Desktop\HackMty\HackMTY2026_CapitalOneTrack\EDA\data\Model_lstm_ae\lstm_autoencoder_artifacts.joblib"
)